### ISSUE TITLE
Error downloading sample file

### ISSUE THREAD

**Issue by eMPee584** [ecoto/iiif_downloader#2]
with python2.7:
```
python2 iiif_downloader.py http://images.iiifhosting.com/iiif/61b59cbe740f6c1ead257e9f6cc7c9f074c0994fca352309e33f2c9ed2044621/info.json images
Traceback (most recent call last):
  File "iiif_downloader.py", line 205, in <module>
    main()
  File "iiif_downloader.py", line 196, in main
    response = requests.get(args.iif_document_url, allow_redirects=True, verify=args.verify_ssl_certificate)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 516, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 459, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 314, in prepare
    self.prepare_url(url, params)
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 382, in prepare_url
    raise InvalidURL(*e.args)
requests.exceptions.InvalidURL: Failed to parse: http://images.iiifhosting.com/iiif/61b59cbe740f6c1ead257e9f6cc7c9f074c0994fca352309e33f2c9ed2044621/info.json

```
with python 3.8.6:
```
python3 iiif_downloader.py http://images.iiifhosting.com/iiif/61b59cbe740f6c1ead257e9f6cc7c9f074c0994fca352309e33f2c9ed2044621/info.json images
Traceback (most recent call last):                                                                                                                 
  File "iiif_downloader.py", line 205, in <module>                                                                                                 
    main()                                                                                                                                         
  File "iiif_downloader.py", line 198, in main                                                                                                     
    if document['@type'] in [ "sc:Collection" ]:                                                                                                   
KeyError: '@type'
```
What did I do wrong.. :thinking:  :sweat_smile:

**Comment by ecoto** [comment]
Hi, the problem is that the URL you are using does not point to a document of type Collection, Manifest, Sequence or Canvas. It is directly pointing to the information or a particular image. Open your browser and enter http://images.iiifhosting.com/iiif/61b59cbe740f6c1ead257e9f6cc7c9f074c0994fca352309e33f2c9ed2044621/ and you will see the image.
